[package]
name = "xelis-blockchain"
version = "0.1.0"
authors = ["Slixe <slixeprivate@gmail.com>"]
edition = "2018"
default-run = "daemon"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.2"
hex = "0.4.3"
num-bigint = "0.4.0"
num-traits = "0.2.14"
num_cpus = "1.13.0"
serde = { version = "1.0.126", features = ["derive", "rc"] }
serde_json = "1.0"
rand = "0.8.4"
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
thiserror = "1.0.30"
log = "0.4"
fern = { version = "0.6", features = ["colored"] }
chrono = "0.4.19"
clap = { version = "3.1.18", features = ["derive"] }
tokio = { version = "1", features = ["rt-multi-thread", "io-util", "io-std", "time", "macros", "sync", "net"] }
bytes = "1"
actix-web = "4"
anyhow = "1.0.57"
reqwest = { version = "0.11.10", features = ["blocking", "json"] }
sled = "0.34.7"
lru = "0.7.8"
async-recursion = "1.0.0"

[[bin]]
name = "wallet"
path = "src/bin/wallet/main.rs"

[[bin]]
name = "miner"
path = "src/bin/miner/main.rs"

[[bin]]
name = "daemon"
path = "src/bin/daemon/main.rs"