[package]
name = "xelis-blockchain"
version = "0.1.0"
authors = ["Slixe <slixeprivate@gmail.com>"]
edition = "2018"
default-run = "blockchain"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crypto-hash = "0.3.4"
hex = "0.4.3"
num-bigint = "0.4.0"
num-traits = "0.2.14"
num_cpus = "1.13.0"
serde = { version = "1.0.126", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.4"
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
thiserror = "1.0.30"
log = "0.4"
fern = { version = "0.6", features = ["colored"] }
chrono = "0.4.19"
argh = "0.1.7"

[[bin]]
name = "blockchain"
path = "src/main.rs"

[[bin]]
name = "wallet"
path = "src/wallet/main.rs"

[[bin]]
name = "daemon"
path = "src/daemon/main.rs"