[package]
name = "xelis_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.2"
hex = "0.4.3"
num-bigint = "0.4.0"
num-traits = "0.2.14"
serde = { version = "1.0.126", features = ["derive", "rc"] }
serde_json = "1.0"
rand = "0.8.4"
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
thiserror = "1.0.30"
anyhow = "1.0.57"
log = "0.4"
fern = "0.6"
chrono = "0.4.19"
tokio = { version = "1", features = ["macros", "signal"] }
reqwest = { version = "0.11.10", features = ["blocking", "json"] }