[package]
name = "xelis_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha3 = "0.10.6"
hex = "0.4.3"
num-bigint = "0.4.0"
num-traits = "0.2.14"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
rand = "0.8.4"
ed25519-dalek = { version = "1.0.1", features = ["serde"] }
thiserror = "1.0.30"
anyhow = "1.0.57"
log = "0.4"
fern = { version = "0.6", features = ["colored"] }
chrono = "0.4.19"
tokio = { version = "1.25", features = ["macros", "signal", "time", "sync"], optional = true }
reqwest = { version = "0.11.10", features = ["json"], optional = true }
lazy_static = "1.4.0"

[features]
json_rpc = ["dep:reqwest"]
prompt = ["dep:tokio"]