[package]
name = "xelis_common"
version = "1.8.0"
edition = "2021"
authors = ["Slixe <slixeprivate@gmail.com>"]
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.5.0"
hex = "0.4.3"
num-bigint = "0.4.0"
num-traits = "0.2.14"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
rand = "0.8.4"
bulletproofs = { git = "https://github.com/cchudant/bulletproofs", branch = "batching-own-repo", version = "5.0.2" }
curve25519-dalek = { version = "4.1.1", features = ["digest", "group", "rand_core", "serde"], git = "https://github.com/cchudant/curve25519-dalek", branch = "main" }
lazy_static = "1.4.0"
sha3 = "0.9.1"

thiserror = "1.0.57"
anyhow = "1.0.57"
log = "0.4"
fern = { version = "0.6", features = ["colored", "date-based"] }
chrono = "0.4.19"
tokio = { version = "1.25", features = ["macros", "signal", "time", "sync"], optional = true }
reqwest = { version = "0.11.10", default-features = false, features = ["json", "rustls"], optional = true }
clap = { version = "3.1.18", features = ["derive"], optional = true }
crossterm = "*"
indexmap = { version = "2.0.0", features = ["serde"] }
actix-rt = { version = "2.8.0", optional = true }
actix-web = { version = "4", optional = true }
actix-ws = { version = "0.2.5", optional = true }
futures-util = { version = "0.3.28", optional = true }
async-trait = { version = "0.1.64", optional = true }
regex = "1"
serde_regex = "1.1.0"
tokio-tungstenite = { version = "0.21", features = ["rustls-tls-native-roots"] }
primitive-types = { version = "0.12.2", features = ["serde"] }

[features]
json_rpc = ["dep:reqwest"]
prompt = ["dep:tokio"]
clap = ["dep:clap"]
rpc_server = ["dep:actix-rt", "dep:actix-web", "dep:actix-ws", "dep:futures-util", "dep:tokio", "dep:async-trait", "dep:reqwest"]
