[package]
name = "xelis_miner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xelis_common = { path = "../xelis_common" }
clap = { version = "3.1.18", features = ["derive"] }
num_cpus = "1.15.0"
tokio-tungstenite = "0.18.0"
futures-util = "0.3.25"

# Common dependencies
log = "0.4"
serde = { version = "1.0.126", features = ["derive", "rc"] }
serde_json = "1.0"
tokio = "1.24.1"
anyhow = "1"
fern = { version = "0.6", features = ["colored"] }