[package]
name = "xelis_miner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xelis_common = { path = "../xelis_common" }
clap = { version = "3.1.18", features = ["derive"] }

# Common dependencies
log = "0.4"
serde = { version = "1.0.126", features = ["derive", "rc"] }
serde_json = "1.0"
tokio = "1.24.1"
anyhow = "1.0.57"