[package]
name = "xelis_wallet"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
xelis_common = { path = "../xelis_common", features = ["json_rpc"] }
chacha20poly1305 = "0.10.1"
sled = "0.34.7"
clap = { version = "3.1.18", features = ["derive"] }
argon2 = "0.4.1"
lazy_static = "1.4.0"

# common dependencies
log = "0.4"
rand = "0.8.4"
thiserror = "1.0.30"
tokio = { version = "1", features = ["rt-multi-thread"]}
anyhow = "1"
fern = { version = "0.6", features = ["colored"] }